name: CI

# Basic style control, to ensure quality on Markdown drafting.

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - dev
      - main

jobs:
  Lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Lint Markdown
        run: ./gradlew spotlessCheck
