name: CI

# Basic style control, to ensure quality on Markdown drafting.

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - dev
      - main

jobs:
  Lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Lint Markdown
        run: ./gradlew spotlessCheck

  Build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"

      - name: Prepare environment
        run: |
          mkdir docs

      - name: Generate PPS report PDF
        uses: docker://pandoc/latex:2.11.4
        with:
          args: -d ./pandoc/pps-report/latex.yaml -o docs/PPSReport.pdf -M date:${{steps.date.outputs.date}}

      - name: Generate LSS report PDF
        uses: docker://pandoc/latex:2.11.4
        with:
          args: -d ./pandoc/lss-report/latex.yaml -o docs/LSSReport.pdf -M date:${{steps.date.outputs.date}}

      - name: Generate appendix documents PDF
        uses: docker://pandoc/latex:2.11.4
        with:
          args: -d ./pandoc/appendix/latex.yaml -o docs/Appendix.pdf -M date:${{steps.date.outputs.date}}

      - name: Generate PPS report HTML
        uses: docker://pandoc/latex:2.11.4
        with:
          args: -d ./pandoc/pps-report/html.yaml -o docs/PPSReport.html

      - name: Generate LSS report HTML
        uses: docker://pandoc/latex:2.11.4
        with:
          args: -d ./pandoc/lss-report/html.yaml -o docs/LSSReport.html

      - name: Generate Appendix documents HTML
        uses: docker://pandoc/latex:2.11.4
        with:
          args: -d ./pandoc/appendix/html.yaml -o docs/Appendix.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports-${{ steps.date.outputs.date }}
          path: docs