name: Reports generation

# Generate new reports release on push on main
on:
  push:
    branches:
      - main

jobs:
  ReportsGeneration:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Use cache if available for Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Merge PPS markdown files
        id: ppsreportfiles
        run: |
          echo "::set-output name=PPS_REPORT_FILES::$(printf '"%s" ' src/markdown/pps-report/*.md)"

      - name: Merge LSS markdown files
        id: lssreportfiles
        run: |
            echo "::set-output name=LSS_REPORT_FILES::$(printf '"%s" ' src/markdown/lss-report/*.md)"

      - name: Create output directory
        run: mkdir report

      - name: PPS report generation
        uses: docker://pandoc/latex:2.11.3.2
        with:
          args: -F pandoc-crossref --output=report/PPSReport.pdf  ${{ steps.ppsreportfiles.outputs.PPS_REPORT_FILES }}

      - name: LSS report generation
        uses: docker://pandoc/latex:2.11.3.2
        with:
         args: -F pandoc-crossref --output=report/LSSReport.pdf  ${{ steps.lssreportfiles.outputs.LSS_REPORT_FILES }}

      # todo print also other documents? (ex. sprint overview)
      - name: Extract version
        run: |
          ./gradlew generateVersionFile

      - name: Generate version
        id: genversion
        run: |
          echo "::set-output name=VERSION::$(cat build/version)"

      - name: Archive as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: report

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: reports-${{ steps.genversion.outputs.VERSION }}
         release_name: Release ${{ steps.genversion.outputs.VERSION }}
         draft: false
         prerelease: false

      - name: Upload Release Assets
        uses: dwenegar/upload-release-assets@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         release_id: ${{ steps.create-release.outputs.id }}
         assets_path: report
