name: Generate release

# Generates a new release, after a release/* branch is successfully
# merged into main. The tag name is inferred from the branch name.
on:
  push:
    branches:
      - feature/html-reports

jobs:
  release:
    name: Generate release

    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout GitHub Pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./gh-pages

      - name: Checkout web template
        run: |
          git clone https://github.com/scalaquest/pandoc-bootstrap.git ./template

      - name: Prepare report generation
        id: reports
        run: |
          echo "::set-output name=PPS_REPORT_MERGED::$(printf '"%s" ' src/markdown/pps-report/*.md)"
          echo "::set-output name=LSS_REPORT_MERGED::$(printf '"%s" ' src/markdown/lss-report/*.md)"
          mkdir report

      - name: Prepare gh-pages environment
        run: |
          rm -rf gh-pages/reports
          mkdir gh-pages/reports -p

      - name: Generate PPS report HTML
        uses: docker://pandoc/latex:2.11.3.2
        with:
          args: ${{ steps.reports.outputs.PPS_REPORT_MERGED }} --o ./gh-pages/reports/pps.html -f markdown --template ./template/template.html --toc --toc-depth=2 -F pandoc-crossref

      - name: Generate LSS report HTML
        uses: docker://pandoc/latex:2.11.3.2
        with:
          args: ${{ steps.reports.outputs.LSS_REPORT_MERGED }} --o ./gh-pages/reports/lss.html -f markdown --template ./template/template.html --toc --toc-depth=2 -F pandoc-crossref

      - name: Push reports to gh-pages
        run: |
          cd gh-pages
          git config user.name Reportbot
          git config user.email github-actions@github.com
          git add reports
          git commit -m "Update reports"
          git push
