name: Stable Branches CI

# Trigger on pull request on the stable branch, and as an additional
# check when pushing on main

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - main
      - dev

jobs:
  StabilityCheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Use cache if available for Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Syntax and Style Check with Spotless
        run: ./gradlew spotlessCheck
